@startuml 3D meteorite impacts vizualization

class Main {
  +startApp() : Promise<void>
  +applyFilters(viewer, data) : void
}

class MeteoriteAPI {
  +fetchMeteorites() : Promise<Array>
}

class NominatimAPI {
  +geocodeLocation(reclong: number, reclat: number) : Promise<object>
}

class Markers {
  +addMarkers(viewer: Viewer, meteorites: Array) : void
}

class Viewer {
  +initViewer() : Viewer
}

class FilterMeteorites {
  +filterMeteorites(data, selectedSize, from, to, location) : Array
}

class Server {
  +GET /api/meteorites : Array
}

Main --> MeteoriteAPI : fetches data
Main --> Markers : renders markers
Main --> FilterMeteorites : filters on user input
Main --> NominatimAPI : geocodes on marker click
MeteoriteAPI --> Server : fetch /api/meteorites
Markers --> Viewer : adds entities
@enduml