@startuml 3D meteorite impacts object diagram

object aachen {
  name = "Aachen"
  recclass = "L5"
  mass = "21"
  fall = "Fell"
  year = "1880-01-01T00:00:00"
  reclat = 50.775
  reclong = 6.08333
}

object viewer {
  timeline = false
  animation = false
}

object dataSource {
  name = "meteorites"
  clustering.enabled = true
  clustering.pixelRange = 180
}

object nominatimResult {
  display_name = "Aachen, Nordrhein-Westfalen, Germany"
  city = "Aachen"
  country = "Germany"
}

object cesiumEntity {
  name = "Aachen"
  position = "Cartesian3(6.08333, 50.775)"
  description = "<h2>Aachen</h2>..."
}

aachen --> nominatimResult : reverseGeocode
aachen --> cesiumEntity : addMarkers
viewer --> dataSource : contains
dataSource --> aachen : entity

@enduml